### ISSUE TITLE
MySQL DB unknown table error

### ISSUE THREAD

**Issue by khanzadyan** [openintegrationhub/jdbc-component#11]
JDBC: MySQL component shows an error when `lookupRowByPrimaryKey`, `upsertRowByPrimaryKey` and `deleteRowByPrimaryKey` action functions are being used. Even though a connection to MySQL database is successful. The reported error has the following form:
```
Error: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown table 'test' in information_schema at io.elastic.jdbc.ColumnNamesWithPrimaryKeyProvider.getColumns(ColumnNamesWithPrimaryKeyProvider.java:95) at io.elastic.jdbc.ColumnNamesWithPrimaryKeyProvider.getMetaModel(ColumnNamesWithPrimaryKeyProvider.java:43) at io.elastic.sailor.ServiceMethods$2.execute(ServiceMethods.java:58) at io.elastic.sailor.Service.executeMethod(Service.java:99) at io.elastic.sailor.Service.getServiceInstanceAndExecute(Service.java:79) at io.elastic.sailor.Service.createServiceInstanceAndExecute(Service.java:70) at io.elastic.sailor.Service.main(Service.java:55) Caused by: java.sql.SQLSyntaxErrorException: Unknown table 'test' in information_schema at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1247) at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3149) at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3137) at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56) at com.mysql.cj.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3190) at io.elastic.jdbc.ColumnNamesWithPrimaryKeyProvider.getColumns(ColumnNamesWithPrimaryKeyProvider.java:71) ... 6 more
```

This happens after the list of tables is shown.

**Comment by umkaline** [comment]
![image](https://user-images.githubusercontent.com/15971237/54991590-f0495480-4fc5-11e9-9b8c-267d968edf20.png)
There is no such table, so error is valid

**Comment by khanzadyan** [comment]
@umkaline Can you please summarise your findings so far? We have established that the specific error is happening with the MySQL server version 5.6. The error is not present on version 8.0.

Can you add something more?

**Comment by umkaline** [comment]
Confirm that error present on the MySQL server version 5.6.
And the table was present and contained PK.

Creds name in the BW `MySQL "no table" issue`

Error listing below:
`

Error: java.lang.RuntimeException: java.sql.SQLSyntaxErrorException: Unknown table 'test' in information_schema at io.elastic.jdbc.ColumnNamesWithPrimaryKeyProvider.getColumns(ColumnNamesWithPrimaryKeyProvider.java:95) at io.elastic.jdbc.ColumnNamesWithPrimaryKeyProvider.getMetaModel(ColumnNamesWithPrimaryKeyProvider.java:43) at io.elastic.sailor.ServiceMethods$2.execute(ServiceMethods.java:58) at io.elastic.sailor.Service.executeMethod(Service.java:99) at io.elastic.sailor.Service.getServiceInstanceAndExecute(Service.java:79) at io.elastic.sailor.Service.createServiceInstanceAndExecute(Service.java:70) at io.elastic.sailor.Service.main(Service.java:55) Caused by: java.sql.SQLSyntaxErrorException: Unknown table 'test' in information_schema at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:95) at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1247) at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3149) at com.mysql.cj.jdbc.DatabaseMetaData$7.forEach(DatabaseMetaData.java:3137) at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56) at com.mysql.cj.jdbc.DatabaseMetaData.getPrimaryKeys(DatabaseMetaData.java:3190) at io.elastic.jdbc.ColumnNamesWithPrimaryKeyProvider.getColumns(ColumnNamesWithPrimaryKeyProvider.java:71) ... 6 more
`
